window.CATEGORY_CATALOG = [
  {
    category: "Congelados",
    supermarketSections: ["Congelados", "Helados", "Pescado congelado", "Verdura congelada"],
    priority: 100,
    words: [
      "congelado",
      "congelada",
      "congelados",
      "hielo",
      "helado",
      "helados",
      "pizza congelada",
      "pizzas congeladas",
      "verdura congelada",
      "guisantes congelados",
      "salteado congelado",
      "croquetas",
      "nuggets",
      "varitas de merluza",
      "calamares congelados",
      "gambas congeladas",
      "marisco congelado",
      "pescado congelado",
    ],
  },
  {
    category: "Limpieza",
    supermarketSections: [
      "Drogueria y limpieza",
      "Limpieza y hogar",
      "Papel y celulosa",
      "Menaje",
    ],
    priority: 90,
    words: [
      "ambientador",
      "bayeta",
      "bayetas",
      "bolsas basura",
      "bolsas de basura",
      "desatascador",
      "desengrasante",
      "desinfectante",
      "detergente",
      "estropajo",
      "estropajos",
      "fregasuelos",
      "gel lavavajillas",
      "guantes",
      "lejia",
      "limpiacristales",
      "limpiador",
      "limpiahogar",
      "lavavajillas",
      "lavaplatos",
      "papel aluminio",
      "papel de cocina",
      "papel higienico",
      "servilletas",
      "suavizante",
      "vinagre limpieza",
      "wc",
    ],
  },
  {
    category: "Frutas y verduras",
    supermarketSections: ["Frescos", "Fruta y verdura", "Verdura", "Ensaladas"],
    priority: 80,
    words: [
      "acelga",
      "acelgas",
      "aguacate",
      "ajo",
      "ajos",
      "alcachofa",
      "apio",
      "arandanos",
      "banana",
      "berenjena",
      "boniato",
      "brocoli",
      "calabacin",
      "calabaza",
      "canónigos",
      "canonigos",
      "cebolla",
      "cebollas",
      "champiñon",
      "champinon",
      "champiñones",
      "champinones",
      "ciruela",
      "coliflor",
      "ensalada",
      "espinaca",
      "espinacas",
      "fresa",
      "fresas",
      "frambuesa",
      "fruta",
      "judia verde",
      "judias verdes",
      "kiwi",
      "lechuga",
      "lima",
      "limon",
      "limones",
      "mandarina",
      "mandarinas",
      "mango",
      "manzana",
      "manzanas",
      "melon",
      "naranja",
      "naranjas",
      "patata",
      "patatas",
      "pepino",
      "pera",
      "peras",
      "pimiento",
      "pimientos",
      "piña",
      "pina",
      "platano",
      "platanos",
      "puerro",
      "rucula",
      "rúcula",
      "seta",
      "setas",
      "tomate",
      "tomates",
      "uva",
      "uvas",
      "verdura",
      "verduras",
      "zanahoria",
      "zanahorias",
    ],
  },
  {
    category: "Carnes y pescados",
    supermarketSections: ["Frescos", "Carne", "Pescado", "Marisco", "Charcuteria"],
    priority: 70,
    words: [
      "albondigas",
      "atun",
      "bacalao",
      "bacon",
      "berberechos",
      "bonito",
      "butifarra",
      "calamar",
      "calamares",
      "carne",
      "cerdo",
      "chistorra",
      "chorizo",
      "chuleta",
      "codillo",
      "conejo",
      "costilla",
      "costillas",
      "dorada",
      "embutido",
      "fiambre",
      "filete",
      "filetes",
      "gamba",
      "gambas",
      "hamburguesa",
      "hamburguesas",
      "jamon",
      "langostino",
      "langostinos",
      "lomo",
      "longaniza",
      "mejillones",
      "merluza",
      "morcilla",
      "pavo",
      "pechuga",
      "pescado",
      "pollo",
      "pulpo",
      "salchicha",
      "salchichas",
      "salmon",
      "sardina",
      "sardinas",
      "sepia",
      "sobrasada",
      "ternera",
      "vacuno",
    ],
  },
  {
    category: "L\u00e1cteos",
    supermarketSections: ["Lacteos", "Huevos leche y mantequilla", "Postres y yogures", "Quesos"],
    priority: 60,
    words: [
      "actimel",
      "batido",
      "batidos",
      "bifidus",
      "brie",
      "camembert",
      "cuajada",
      "flan",
      "huevo",
      "huevos",
      "kefir",
      "leche",
      "mantequilla",
      "margarina",
      "mozzarella",
      "natillas",
      "nata",
      "parmesano",
      "postre lacteo",
      "queso",
      "quesitos",
      "yogur",
      "yogures",
      "yogurt",
    ],
  },
  {
    category: "Panader\u00eda",
    supermarketSections: ["Panaderia", "Panaderia, bolleria y pasteleria", "Pan de horno"],
    priority: 50,
    words: [
      "bagel",
      "baguette",
      "barra",
      "bizcocho",
      "bolleria",
      "bollo",
      "brioche",
      "churros",
      "croissant",
      "donut",
      "empanada",
      "galleta",
      "galletas",
      "hogaza",
      "magdalena",
      "magdalenas",
      "napolitana",
      "pan",
      "pan de molde",
      "pan hamburguesa",
      "pan rallado",
      "picos",
      "rosquilletas",
      "tostadas",
    ],
  },
  {
    category: "Bebidas",
    supermarketSections: ["Bebidas", "Agua y refrescos", "Bodega", "Zumos"],
    priority: 40,
    words: [
      "agua",
      "aquarius",
      "batido chocolate",
      "bitter",
      "cava",
      "cerveza",
      "cervezas",
      "cocacola",
      "coca cola",
      "cola",
      "fanta",
      "gaseosa",
      "isotonica",
      "refresco",
      "refrescos",
      "ron",
      "sangria",
      "sidra",
      "tonica",
      "tónica",
      "vino",
      "vodka",
      "whisky",
      "zumo",
      "zumos",
    ],
  },
  {
    category: "Otros",
    supermarketSections: ["La Despensa", "Alimentacion general", "Despensa"],
    priority: 10,
    words: [
      "aceite",
      "aceitunas",
      "alubia",
      "alubias",
      "arroz",
      "azucar",
      "cacao",
      "cafe",
      "caldo",
      "caramelos",
      "cereales",
      "chocolate",
      "conserva",
      "conservas",
      "especia",
      "especias",
      "garbanzo",
      "garbanzos",
      "harina",
      "infusion",
      "infusiones",
      "ketchup",
      "lenteja",
      "lentejas",
      "mayonesa",
      "mermelada",
      "miel",
      "mostaza",
      "pasta",
      "sal",
      "salsa",
      "salsas",
      "sopa",
      "tortillas",
      "vinagre",
    ],
  },
];
